import * as vscode from 'vscode';
import { AgentEvent, SessionStats } from '../agent/types';

export class ChatPanel {
  private static current?: ChatPanel;

  private constructor(
    private readonly panel: vscode.WebviewPanel,
    private readonly submit: (text: string) => Promise<void>,
    private readonly actions: {
      newSession(): void; clearSession(): void; stop(): void; addFiles(): void;
      addSkill(): void; addMcp(): void; history(): void; loadSession(id: string): void; deleteSession(id: string): void; togglePin(id: string): void; toggleAutoApprove(): void; toggleLightMode(): void; setAgentMode(mode: string): void; toggleAutoCollapseReasoning(): void; toggleAutoCollapseToolCalls(): void;
    }
  ) {
    panel.webview.html = this.html();
    panel.webview.onDidReceiveMessage(async message => {
      if (message.type === 'send') await this.submit(String(message.text));
      if (message.type === 'new') this.actions.newSession();
      if (message.type === 'clear') this.actions.clearSession();
      if (message.type === 'stop') this.actions.stop();
      if (message.type === 'addFiles') this.actions.addFiles();
      if (message.type === 'addSkill') this.actions.addSkill();
      if (message.type === 'addMcp') this.actions.addMcp();
      if (message.type === 'history') this.actions.history();
      if (message.type === 'loadSession') this.actions.loadSession(String(message.id));
      if (message.type === 'deleteSession') this.actions.deleteSession(String(message.id));
      if (message.type === 'togglePin') this.actions.togglePin(String(message.id));
      if (message.type === 'toggleAutoApprove') this.actions.toggleAutoApprove();
      if (message.type === 'toggleLightMode') this.actions.toggleLightMode();
      if (message.type === 'setAgentMode') this.actions.setAgentMode(String(message.mode));
      if (message.type === 'toggleAutoCollapseReasoning') this.actions.toggleAutoCollapseReasoning();
      if (message.type === 'toggleAutoCollapseToolCalls') this.actions.toggleAutoCollapseToolCalls();
    });
    panel.onDidDispose(() => { if (ChatPanel.current?.panel === panel) ChatPanel.current = undefined; });
  }

  static show(context: vscode.ExtensionContext, submit: (text: string) => Promise<void>, actions: ChatPanel['actions']) {
    if (ChatPanel.current) { ChatPanel.current.panel.reveal(); return ChatPanel.current; }
    const panel = vscode.window.createWebviewPanel('localAgent.chat', 'NIGHTFALL', vscode.ViewColumn.Beside, { enableScripts: true, retainContextWhenHidden: true });
    ChatPanel.current = new ChatPanel(panel, submit, actions);
    return ChatPanel.current;
  }

  add(event: AgentEvent) { this.panel.webview.postMessage(event); }
  clear() { this.panel.webview.postMessage({ type: 'clearMessages' }); }
  history(sessions: Array<{ id: string; title: string; updatedAt: number; pinned: boolean }>) { this.panel.webview.postMessage({ type: 'history', sessions }); }
  restore(messages: Array<{ role: string; content: string | null }>) { this.panel.webview.postMessage({ type: 'restore', messages }); }
  metrics(stats: SessionStats | undefined) { const inputTokens = stats?.inputTokens || 0; const outputTokens = stats?.outputTokens || 0; const tokensPerSecond = stats?.elapsedMs ? outputTokens / (stats.elapsedMs / 1000) : 0; this.panel.webview.postMessage({ type: 'sessionMetrics', inputTokens, outputTokens, tokensPerSecond }); }
  setAutoApprove(enabled: boolean) { this.panel.webview.postMessage({ type: 'autoApprove', enabled }); }
  setLightMode(enabled: boolean) { this.panel.webview.postMessage({ type: 'lightMode', enabled }); }
  setAgentMode(mode: string) { this.panel.webview.postMessage({ type: 'agentMode', mode }); }
  setAutoCollapseReasoning(enabled: boolean) { this.panel.webview.postMessage({ type: 'autoCollapseReasoning', enabled }); }
  setAutoCollapseToolCalls(enabled: boolean) { this.panel.webview.postMessage({ type: 'autoCollapseToolCalls', enabled }); }

  private html() {
    const nonce = String(Date.now());
    return `<!doctype html>
<html><head><meta charset="UTF-8"><style>
:root{--background:#09090b;--foreground:#fafafa;--muted:#a1a1aa;--card:#18181b;--field:#27272a;--border:#27272a;--primary:#fafafa;--primary-foreground:#18181b;--accent:#27272a;--accent-foreground:#fafafa;--destructive:#ef4444;--radius:8px}
*{box-sizing:border-box}body{margin:0;padding:20px;min-width:280px;color:var(--foreground);background:var(--background);font:400 14px Inter,ui-sans-serif,system-ui,sans-serif;line-height:1.45;transition:background .15s,color .15s}.light{--background:#fff;--foreground:#18181b;--muted:#71717a;--card:#fff;--field:#fafafa;--border:#e4e4e7;--primary:#18181b;--primary-foreground:#fafafa;--accent:#f4f4f5;--accent-foreground:#18181b;--destructive:#dc2626}
header{display:flex;align-items:center;justify-content:space-between;gap:12px;border:1px solid var(--border);border-radius:var(--radius);background:var(--card);padding:13px 15px;box-shadow:0 1px 2px #0003;margin-bottom:8px}
h1{font-size:16px;line-height:1;margin:0;font-weight:700;letter-spacing:.2px}.tag{border:1px solid var(--border);border-radius:999px;background:var(--accent);color:var(--accent-foreground);padding:4px 8px;font-size:10px;font-weight:600;white-space:nowrap}
.panel{border:1px solid var(--border);border-radius:var(--radius);background:var(--card);box-shadow:0 1px 2px #0002;padding:12px}#messages{min-height:50vh;max-height:58vh;overflow:auto;padding:2px}
.msg{white-space:pre-wrap;margin:10px 0;padding:10px 12px;border:1px solid var(--border);border-radius:var(--radius);background:var(--accent);color:var(--accent-foreground)}.user{background:var(--primary);color:var(--primary-foreground)}.assistant{background:var(--card)}.tool,.status{font-size:12px}.error{background:#7f1d1d;color:#fee2e2}.reasoning,.collapsible{margin:10px 0;border:1px solid var(--border);border-radius:var(--radius);background:var(--field);color:var(--muted);font-size:12px}.reasoning summary,.collapsible summary{cursor:pointer;padding:8px 10px;font-weight:700;letter-spacing:.2px}.reasoning-content{padding:0 10px 9px;white-space:pre-wrap}.collapsible-content{max-height:260px;overflow:auto;resize:vertical;padding:0 10px 9px;white-space:pre-wrap}
textarea{display:block;width:100%;background:var(--field);color:var(--foreground);border:1px solid var(--border);border-radius:var(--radius);padding:11px;font:400 14px Inter,ui-sans-serif,system-ui,sans-serif;resize:vertical;outline:none}textarea:focus{border-color:var(--foreground);box-shadow:0 0 0 2px #71717a44}
select{background:var(--field);color:var(--foreground);border:1px solid var(--border);border-radius:var(--radius);padding:7px 10px;font:600 12px Inter,ui-sans-serif,system-ui,sans-serif}#modeDescription{display:block;color:var(--muted);font-size:12px;margin:7px 2px}
button{margin:9px 5px 0 0;padding:7px 10px;background:transparent;color:var(--foreground);border:1px solid var(--border);border-radius:var(--radius);box-shadow:none;font:600 12px Inter,ui-sans-serif,system-ui,sans-serif;cursor:pointer;transition:background .12s,border-color .12s,color .12s}button:hover{background:var(--accent);border-color:#71717a;color:var(--accent-foreground)}button:active{background:var(--border)}button:disabled{opacity:.45;cursor:not-allowed}#send{background:var(--primary);border-color:var(--primary);color:var(--primary-foreground);font-weight:700}#send:hover{opacity:.9}#stop{color:var(--destructive);border-color:var(--destructive)}#autoApprove.active,#lightMode.active,#autoCollapseReasoning.active{background:var(--primary);border-color:var(--primary);color:var(--primary-foreground)}
#history{display:none;margin-top:14px;padding-top:12px;border-top:1px solid var(--border)}.session{display:block;width:100%;text-align:left;background:var(--field);color:var(--foreground);margin:7px 0}
#metrics{color:var(--muted);font-size:11px;margin:0 2px 14px;letter-spacing:.2px}
.collapsible{margin:10px 0;border:1px solid var(--border);border-radius:var(--radius);background:var(--field);color:var(--muted);font-size:12px}.collapsible summary{cursor:pointer;padding:8px 10px;font-weight:700;letter-spacing:.2px}.collapsible-content{max-height:260px;overflow:auto;resize:vertical;padding:0 10px 9px;white-space:pre-wrap}
.assistant p{margin:8px 0}.assistant h1,.assistant h2,.assistant h3,.assistant h4,.assistant h5,.assistant h6{margin:12px 0 6px}.assistant ul,.assistant ol{margin:7px 0;padding-left:24px}.assistant li{margin:3px 0}.assistant table{border-collapse:collapse;width:100%;margin:10px 0;font-size:12px}.assistant th,.assistant td{border:1px solid var(--border);padding:6px 8px;text-align:left;vertical-align:top}.assistant th{background:var(--accent);font-weight:700}.assistant pre{overflow:auto;resize:vertical;max-height:360px;padding:10px;background:var(--field);border:1px solid var(--border);border-radius:6px}.assistant code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.92em;background:var(--field);padding:1px 4px;border-radius:4px}.assistant pre code{background:transparent;padding:0}.assistant a{color:inherit;text-decoration:underline}
</style></head><body>
<header><h1>NIGHTFALL</h1><span class="tag">LOCAL / READY</span></header><div id="metrics">TOKENS 0 IN · 0 OUT · — TOK/S</div>
<section class="panel"><div id="messages"></div><label for="agentMode">AGENT</label><select id="agentMode"><option value="ask">ask</option><option value="code" selected>code</option><option value="debug">debug</option><option value="explore">explore</option><option value="general">general</option><option value="plan">plan</option></select><span id="modeDescription">The default agent. Executes tools based on configured permissions.</span><textarea id="input" rows="4" placeholder="Ask the local agent..."></textarea>
<div><button id="send">SEND</button><button id="stop">STOP</button><button id="autoApprove">AUTO-APPROVE: OFF</button><button id="lightMode">LIGHT MODE</button><button id="autoCollapseReasoning" title="Collapse reasoning blocks after the agent finishes writing them.">AUTO-COLLAPSE REASONING: ON</button><button id="autoCollapseToolCalls" title="Collapse tool calls after they finish. Expand and drag the contents to inspect them.">AUTO-COLLAPSE TOOL CALLS: ON</button><button id="files">+ FILES</button><button id="skill">+ SKILL</button><button id="mcp">+ MCP</button><button id="historyBtn">HISTORY</button><button id="new">NEW SESSION</button><button id="clear">CLEAR</button></div><div id="history"></div></section>
<script nonce="${nonce}">
const vscode=acquireVsCodeApi(),box=document.getElementById('messages'),input=document.getElementById('input'),send=document.getElementById('send'),autoBtn=document.getElementById('autoApprove'),lightBtn=document.getElementById('lightMode'),autoCollapseBtn=document.getElementById('autoCollapseReasoning'),agentMode=document.getElementById('agentMode'),modeDescription=document.getElementById('modeDescription'),history=document.getElementById('history'),metrics=document.getElementById('metrics');let totalIn=0,totalOut=0,autoApprove=false,lightMode=false,autoCollapseReasoning=true;
function plainText(text){return String(text||'').split('\\n').map(line=>{const trimmed=line.trimStart();if(/^#{1,6} /.test(trimmed))return trimmed.replace(/^#{1,6} /,'');if(/^[-*+] /.test(trimmed))return '• '+trimmed.slice(2);return line}).join('\\n').split('**').join('').split('__').join('').split(String.fromCharCode(96)).join('').trim()}
const autoCollapseToolCallsBtn=document.getElementById('autoCollapseToolCalls');let autoCollapseToolCalls=true;
function addCollapsible(title,text){const details=document.createElement('details');details.className='collapsible';details.open=!autoCollapseToolCalls;const summary=document.createElement('summary');summary.textContent=title;const content=document.createElement('div');content.className='collapsible-content';content.textContent=String(text||'');details.append(summary,content);box.appendChild(details);details.scrollIntoView()}
function inlineMarkdown(text){const escaped=String(text||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'),tick=String.fromCharCode(96),codePattern=new RegExp(tick+'([^'+tick+']+)'+tick,'g'),linkPattern=new RegExp('[[]([^]]+)[]][(](https?://[^ )]+)[)]','g');return escaped.replace(codePattern,'<code>$1</code>').replace(/[*][*]([^*]+)[*][*]/g,'<strong>$1</strong>').replace(/__([^_]+)__/g,'<strong>$1</strong>').replace(linkPattern,'<a href="$2" target="_blank" rel="noreferrer">$1</a>')}
function renderMarkdown(parent,text){const lines=String(text||'').replace(/^AGENT:\s*/,'').split(/\\r?\\n/),fence=String.fromCharCode(96).repeat(3);let i=0,inCode=false,code=[];while(i<lines.length){const line=lines[i];if(line.trimStart().startsWith(fence)){if(inCode){const pre=document.createElement('pre'),codeEl=document.createElement('code');codeEl.textContent=code.join('\\n');pre.appendChild(codeEl);parent.appendChild(pre);code=[];inCode=false}else inCode=true;i++;continue}if(inCode){code.push(line);i++;continue}if(!line.trim()){i++;continue}const tableSep=lines[i+1]&&/^\\s*\\|?\\s*:?-{3,}:?\\s*(?:\\|\\s*:?-{3,}:?\\s*)+\\|?\\s*$/.test(lines[i+1]);if(tableSep){const table=document.createElement('table'),head=document.createElement('thead'),body=document.createElement('tbody');const cells=s=>s.trim().replace(/^\\|/,'').replace(/\\|$/,'').split('|').map(x=>x.trim());const tr=document.createElement('tr');cells(line).forEach(cell=>{const th=document.createElement('th');th.innerHTML=inlineMarkdown(cell);tr.appendChild(th)});head.appendChild(tr);table.appendChild(head);i+=2;while(i<lines.length&&lines[i].trim()&&lines[i].includes('|')){const row=document.createElement('tr');cells(lines[i]).forEach(cell=>{const td=document.createElement('td');td.innerHTML=inlineMarkdown(cell);row.appendChild(td)});body.appendChild(row);i++}table.appendChild(body);parent.appendChild(table);continue}const heading=line.match(/^\\s*(#{1,6})\\s+(.+)$/);if(heading){const h=document.createElement('h'+heading[1].length);h.innerHTML=inlineMarkdown(heading[2]);parent.appendChild(h);i++;continue}if(/^\\s*[-*+]\\s+/.test(line)){const list=document.createElement('ul');while(i<lines.length&&/^\\s*[-*+]\\s+/.test(lines[i])){const li=document.createElement('li');li.innerHTML=inlineMarkdown(lines[i].replace(/^\\s*[-*+]\\s+/,''));list.appendChild(li);i++}parent.appendChild(list);continue}if(/^\\s*\\d+[.)]\\s+/.test(line)){const list=document.createElement('ol');while(i<lines.length&&/^\\s*\\d+[.)]\\s+/.test(lines[i])){const li=document.createElement('li');li.innerHTML=inlineMarkdown(lines[i].replace(/^\\s*\\d+[.)]\\s+/,''));list.appendChild(li);i++}parent.appendChild(list);continue}const paragraph=[];while(i<lines.length&&lines[i].trim()&&!/^\\s*(#{1,6})\\s+/.test(lines[i])&&!/^\\s*[-*+]\\s+/.test(lines[i])&&!/^\\s*\\d+[.)]\\s+/.test(lines[i])&&!lines[i].trimStart().startsWith(fence)&&!(lines[i+1]&&/^\\s*\\|?\\s*:?-{3,}:?\\s*(?:\\|\\s*:?-{3,}:?\\s*)+\\|?\\s*$/.test(lines[i+1]))){paragraph.push(lines[i++])}const p=document.createElement('p');p.innerHTML=inlineMarkdown(paragraph.join('\\n'));parent.appendChild(p)}if(inCode){const pre=document.createElement('pre');pre.textContent=code.join('\\n');parent.appendChild(pre)}}
function add(cls,text){if(cls==='tool'){addCollapsible(text.startsWith('TOOL:')?'TOOL CALL':'TOOL RESULT',text);return}if(cls!=='assistant'){const d=document.createElement('div');d.className='msg '+cls;d.textContent=text;box.appendChild(d);d.scrollIntoView();return}const wrapper=document.createElement('div');wrapper.className='msg assistant';const source=String(text||''),pattern=/(?:<(?:think|thinking|reasoning)>)?([\\s\\S]*?)<\\/(?:think|thinking|reasoning)>/gi;let cursor=0,match;while((match=pattern.exec(source))){if(match.index>cursor){const answer=document.createElement('div');renderMarkdown(answer,source.slice(cursor,match.index));wrapper.appendChild(answer)}const details=document.createElement('details');details.className='reasoning';details.open=!autoCollapseReasoning;const summary=document.createElement('summary');summary.textContent='REASONING';const content=document.createElement('div');content.className='reasoning-content';content.textContent=plainText(match[1]);details.append(summary,content);wrapper.appendChild(details);cursor=pattern.lastIndex}if(cursor<source.length||!wrapper.childNodes.length){const answer=document.createElement('div');renderMarkdown(answer,source.slice(cursor));wrapper.appendChild(answer)}box.appendChild(wrapper);wrapper.scrollIntoView()}
send.onclick=()=>{if(input.value.trim()){add('user','YOU: '+input.value);vscode.postMessage({type:'send',text:input.value});input.value='';send.disabled=true}};
document.getElementById('stop').onclick=()=>vscode.postMessage({type:'stop'});autoBtn.onclick=()=>vscode.postMessage({type:'toggleAutoApprove'});lightBtn.onclick=()=>vscode.postMessage({type:'toggleLightMode'});autoCollapseBtn.onclick=()=>vscode.postMessage({type:'toggleAutoCollapseReasoning'});document.getElementById('files').onclick=()=>vscode.postMessage({type:'addFiles'});document.getElementById('skill').onclick=()=>vscode.postMessage({type:'addSkill'});document.getElementById('mcp').onclick=()=>vscode.postMessage({type:'addMcp'});document.getElementById('historyBtn').onclick=()=>vscode.postMessage({type:'history'});document.getElementById('new').onclick=()=>vscode.postMessage({type:'new'});document.getElementById('clear').onclick=()=>{box.innerHTML='';vscode.postMessage({type:'clear'})};
agentMode.onchange=()=>vscode.postMessage({type:'setAgentMode',mode:agentMode.value});
autoCollapseToolCallsBtn.onclick=()=>vscode.postMessage({type:'toggleAutoCollapseToolCalls'});
function setAutoApprove(enabled){autoApprove=Boolean(enabled);autoBtn.textContent=autoApprove?'AUTO-APPROVE: ON':'AUTO-APPROVE: OFF';autoBtn.classList.toggle('active',autoApprove)}function setLightMode(enabled){lightMode=Boolean(enabled);document.body.classList.toggle('light',lightMode);lightBtn.textContent=lightMode?'DARK MODE':'LIGHT MODE';lightBtn.classList.toggle('active',lightMode)}function setAutoCollapseReasoning(enabled){autoCollapseReasoning=Boolean(enabled);autoCollapseBtn.textContent=autoCollapseReasoning?'AUTO-COLLAPSE REASONING: ON':'AUTO-COLLAPSE REASONING: OFF';autoCollapseBtn.classList.toggle('active',autoCollapseReasoning)}
function setAutoCollapseToolCalls(enabled){autoCollapseToolCalls=Boolean(enabled);autoCollapseToolCallsBtn.textContent=autoCollapseToolCalls?'AUTO-COLLAPSE TOOL CALLS: ON':'AUTO-COLLAPSE TOOL CALLS: OFF';autoCollapseToolCallsBtn.classList.toggle('active',autoCollapseToolCalls)}
function setAgentMode(mode){const descriptions={ask:'Get answers and explanations without making codebase changes.',code:'The default agent. Executes tools based on configured permissions.',debug:'Diagnose and fix software issues systematically.',explore:'Fast codebase exploration subagent for finding files, patterns, and answers.',general:'General-purpose subagent for complex, multi-step tasks.',plan:'Plan mode. Only edit Markdown plan files under docs/ or .agents/.'};agentMode.value=mode;modeDescription.textContent=descriptions[mode]||descriptions.code}
window.addEventListener('message',e=>{if(e.data.type==='autoCollapseReasoning')setAutoCollapseReasoning(e.data.enabled)});
window.addEventListener('message',e=>{if(e.data.type==='autoCollapseToolCalls')setAutoCollapseToolCalls(e.data.enabled)});
window.addEventListener('message',e=>{if(e.data.type==='agentMode')setAgentMode(e.data.mode)});
window.addEventListener('message',e=>{const m=e.data;if(m.type==='clearMessages'){box.innerHTML='';totalIn=0;totalOut=0;setAutoApprove(false);metrics.textContent='TOKENS 0 IN · 0 OUT · — TOK/S'}else if(m.type==='autoApprove'){setAutoApprove(m.enabled)}else if(m.type==='lightMode'){setLightMode(m.enabled)}else if(m.type==='assistant'){add('assistant','AGENT: '+(m.text||''));send.disabled=false}else if(m.type==='tool_call')add('tool','TOOL: '+m.tool+' '+JSON.stringify(m.args||{}));else if(m.type==='tool_result')add('tool','RESULT: '+(m.text||''));else if(m.type==='approval')add('tool','APPROVAL: '+(m.text||''));else if(m.type==='error'){add('error','ERROR: '+(m.text||''));send.disabled=false}else if(m.type==='status'){add('status',m.text==='running'?'AGENT IS RUNNING...':'AGENT '+m.text.toUpperCase()+'.');send.disabled=m.text==='running'}else if(m.type==='metrics'){totalIn+=m.inputTokens||0;totalOut+=m.outputTokens||0;metrics.textContent='TOKENS '+totalIn+' IN · '+totalOut+' OUT · '+(m.tokensPerSecond?m.tokensPerSecond.toFixed(1):'—')+' TOK/S'}else if(m.type==='history'){history.style.display='block';history.innerHTML='<b>OLD SESSIONS</b>';if(!m.sessions.length)history.innerHTML+='<div>NO SAVED SESSIONS YET.</div>';m.sessions.forEach(s=>{const row=document.createElement('div'),load=document.createElement('button'),pin=document.createElement('button'),del=document.createElement('button');load.className='session';load.textContent=(s.pinned?'★ ':'')+s.title+' · '+new Date(s.updatedAt).toLocaleString();load.onclick=()=>vscode.postMessage({type:'loadSession',id:s.id});pin.textContent=s.pinned?'UNPIN':'PIN';pin.onclick=()=>vscode.postMessage({type:'togglePin',id:s.id});del.textContent='DELETE';del.onclick=()=>vscode.postMessage({type:'deleteSession',id:s.id});row.appendChild(load);row.appendChild(pin);row.appendChild(del);history.appendChild(row)})}else if(m.type==='restore'){box.innerHTML='';m.messages.forEach(message=>{if(message.role==='user')add('user','YOU: '+(message.content||''));else if(message.role==='assistant')add('assistant','AGENT: '+(message.content||''))})}else if(m.type==='sessionMetrics'){totalIn=m.inputTokens||0;totalOut=m.outputTokens||0;metrics.textContent='TOKENS '+totalIn+' IN · '+totalOut+' OUT · '+(m.tokensPerSecond?m.tokensPerSecond.toFixed(1):'—')+' TOK/S'}});
</script></body></html>`;
  }
}
